module.exports = {
    figures: {
        'eggman': {name: 'eggman', position: {x: 0, y: 0, z: 0}, scale: 0.01, rotation: {x: 0, y: 0, z: 0}},
        'untitled-scene': {name: 'untitled-scene', position: {x: 0, y: 0, z: 0}, scale: 0.01, rotation: {x: 0, y: 0, z: 0}},
        'flowey-the-flower': {name: 'flowey-the-flower', position: {x: 0, y: 0, z: 0}, scale: 0.01, rotation: {x: 0, y: 0, z: 0}},
        'brittany-is-a-bitch': {name: 'brittany-is-a-bitch', position: {x: 0, y: 0, z: 0}, scale: 1, rotation: {x: 0, y: 0, z: 0}},
        'animal-1': {name: 'animal-1', position: {x: 0, y: 0, z: 0}, scale: 1, rotation: {x: 0, y: 0, z: 0}},
        'mountain': {name: 'mountain', position: {x: 0, y: 0, z: 0}, scale: 0.01, rotation: {x: 0, y: 0, z: 0}},
        'grass-plant': {name: 'grass-plant', position: {x: 0, y: 0, z: 0}, scale: 0.1, rotation: {x: 0, y: 0, z: 0}},
        'coconut-tree': {name: 'coconut-tree', position: {x: 0, y: 0, z: 0}, scale: 0.001, rotation: {x: 0, y: 0, z: 0}},

        'tree-05': {name: 'tree-05', position: {x: 0, y: 0, z: 0}, scale: 0.01, rotation: {x: 0, y: 0, z: 0}},
        'tree-toon': {name: 'tree-toon', position: {x: 0, y: 0, z: 0}, scale: 0.1, rotation: {x: 0, y: 0, z: 0}},
        'tree': {name: 'tree', position: {x: 0, y: 0, z: 0}, scale: 0.0001, rotation: {x: 0, y: 0, z: 0}},
        'tree-1-fixed-3': {name: 'tree-1-fixed-3', position: {x: 0, y: 0, z: 0}, scale: 0.01, rotation: {x: 0, y: 0, z: 0}},

        'rock': {name: 'rock', position: {x: 0, y: 0, z: 0}, scale: 0.01, rotation: {x: 0, y: 0, z: 0}},
        'candy-rocks': {name: 'candy-rocks', position: {x: 0, y: 0, z: 0}, scale: 0.1, rotation: {x: 0, y: 0, z: 0}},
        'dragons-attack': {name: 'dragons-attack', position: {x: 0, y: 0, z: 0}, scale: 0.001, rotation: {x: 0, y: 0, z: 0}},
        'lion-cub': {name: 'lion-cub', position: {x: 0, y: 0, z: 0}, scale: 0.05, rotation: {x: 0, y: 0, z: 0}},
        'zebra': {name: 'zebra', position: {x: 0, y: 0, z: 0}, scale: 0.001, rotation: {x: 0, y: 0, z: 0}},
        'raven': {name: 'raven', position: {x: 0, y: 0, z: 0}, scale: 0.1, rotation: {x: 0, y: 0, z: 0}},
        'rabbit': {name: 'rabbit', position: {x: 0, y: 0, z: 0}, scale: 0.1, rotation: {x: 0, y: 0, z: 0}},
        'dog': {name: 'dog', position: {x: 0, y: 0, z: 0}, scale: 0.0001, rotation: {x: 0, y: 0, z: 0}},
        'dog2': {name: 'dog', position: {x: 0, y: 0, z: 0}, scale: 0.0001, rotation: {x: 0, y: 0, z: 0}},
        'giraffe': {name: 'giraffe', position: {x: 0, y: 0, z: 0}, scale: 0.01, rotation: {x: 0, y: 0, z: 0}},


        'condor': {name: 'condor', position: {x: 0, y: 0, z: 0}, scale: 0.1, rotation: {x: 0, y: 0, z: 0}},
        'dove': {name: 'dove', position: {x: 0, y: 0, z: 0}, scale: 0.1, rotation: {x: 0, y: 0, z: 0}},
        'goose': {name: 'goose', position: {x: 0, y: 0, z: 0}, scale: 0.1, rotation: {x: 0, y: 0, z: 0}},
        'gull': {name: 'gull', position: {x: 0, y: 0, z: 0}, scale: 0.1, rotation: {x: 0, y: 0, z: 0}},
        'humbird': {name: 'humbird', position: {x: 0, y: 0, z: 0}, scale: 0.1, rotation: {x: 0, y: 0, z: 0}},
        'penguin': {name: 'penguin', position: {x: 0, y: 0, z: 0}, scale: 0.1, rotation: {x: 0, y: 0, z: 0}},

        //Start alpha room assets
        'tree-1': {name: 'tree-toon', position: {x: -2, y: -1.5, z: -1}, scale: 0.1, rotation: {x: 0, y: 0, z: 0}},
        'tree-2': {name: 'tree-toon', position: {x: -1.5, y: -1.5, z: -1}, scale: 0.1, rotation: {x: 0, y: 0, z: 0}},
        'tree-3': {name: 'tree-toon', position: {x: -1, y: -1.5, z: -1}, scale: 0.1, rotation: {x: 0, y: 0, z: 0}},
        'tree-4': {name: 'tree-toon', position: {x: -0.5, y: -1.5, z: -1}, scale: 0.1, rotation: {x: 0, y: 0, z: 0}},
        'tree-5': {name: 'tree-toon', position: {x: 0, y: -1.5, z: -1}, scale: 0.1, rotation: {x: 0, y: 0, z: 0}},
        'tree-6': {name: 'tree-toon', position: {x: 0.5, y: -1.5, z: -1}, scale: 0.1, rotation: {x: 0, y: 0, z: 0}},
        'tree-7': {name: 'tree-toon', position: {x: 1, y: -1.5, z: -1}, scale: 0.1, rotation: {x: 0, y: 0, z: 0}},
        'tree-8': {name: 'tree-toon', position: {x: 1.5, y: -1.5, z: -1}, scale: 0.1, rotation: {x: 0, y: 0, z: 0}},
        'tree-9': {name: 'tree-toon', position: {x: 2, y: -1.5, z: -1}, scale: 0.1, rotation: {x: 0, y: 0, z: 0}},
        'mountain-1': {name: 'mountain', position: {x: 0, y: -0.75, z: -2.5}, scale: 0.025, rotation: {x: 0, y: 90, z: 0}},
        'grass-plant-1': {name: 'grass-plant', position: {x: -2, y: -1.5, z: 0}, scale: 0.025, rotation: {x: 0, y: 0, z: 0}},
        'grass-plant-2': {name: 'grass-plant', position: {x: -1.75, y: -1.5, z: 0}, scale: 0.025, rotation: {x: 0, y: 0, z: 0}},
        'grass-plant-3': {name: 'grass-plant', position: {x: -1.5, y: -1.5, z: 0}, scale: 0.025, rotation: {x: 0, y: 0, z: 0}},
        'grass-plant-4': {name: 'grass-plant', position: {x: -1.25, y: -1.5, z: 0}, scale: 0.025, rotation: {x: 0, y: 0, z: 0}},
        'grass-plant-5': {name: 'grass-plant', position: {x: -1, y: -1.5, z: 0}, scale: 0.025, rotation: {x: 0, y: 0, z: 0}},
        'grass-plant-6': {name: 'grass-plant', position: {x: -0.75, y: -1.5, z: 0}, scale: 0.025, rotation: {x: 0, y: 0, z: 0}},
        'grass-plant-7': {name: 'grass-plant', position: {x: -0.5, y: -1.5, z: 0}, scale: 0.025, rotation: {x: 0, y: 0, z: 0}},
        'grass-plant-8': {name: 'grass-plant', position: {x: -0.25, y: -1.5, z: 0}, scale: 0.025, rotation: {x: 0, y: 0, z: 0}},
        'grass-plant-9': {name: 'grass-plant', position: {x: 0, y: -1.5, z: 0}, scale: 0.025, rotation: {x: 0, y: 0, z: 0}},
        'grass-plant-10': {name: 'grass-plant', position: {x: 0.25, y: -1.5, z: 0}, scale: 0.025, rotation: {x: 0, y: 0, z: 0}},
        'grass-plant-11': {name: 'grass-plant', position: {x: 0.5, y: -1.5, z: 0}, scale: 0.025, rotation: {x: 0, y: 0, z: 0}},
        'grass-plant-12': {name: 'grass-plant', position: {x: 0.75, y: -1.5, z: 0}, scale: 0.025, rotation: {x: 0, y: 0, z: 0}},
        'grass-plant-13': {name: 'grass-plant', position: {x: 1, y: -1.5, z: 0}, scale: 0.025, rotation: {x: 0, y: 0, z: 0}},
        'grass-plant-14': {name: 'grass-plant', position: {x: 1.25, y: -1.5, z: 0}, scale: 0.025, rotation: {x: 0, y: 0, z: 0}},
        'grass-plant-15': {name: 'grass-plant', position: {x: 1.5, y: -1.5, z: 0}, scale: 0.025, rotation: {x: 0, y: 0, z: 0}},
        'grass-plant-16': {name: 'grass-plant', position: {x: 1.75, y: -1.5, z: 0}, scale: 0.025, rotation: {x: 0, y: 0, z: 0}},
        'grass-plant-17': {name: 'grass-plant', position: {x: 2, y: -1.5, z: 0}, scale: 0.025, rotation: {x: 0, y: 0, z: 0}},

        'grass-plant-18': {name: 'grass-plant', position: {x: -2, y: -1.5, z: -0.5}, scale: 0.025, rotation: {x: 0, y: 0, z: 0}},
        'grass-plant-19': {name: 'grass-plant', position: {x: -1.75, y: -1.5, z: -0.5}, scale: 0.025, rotation: {x: 0, y: 0, z: 0}},
        'grass-plant-20': {name: 'grass-plant', position: {x: -1.5, y: -1.5, z: -0.5}, scale: 0.025, rotation: {x: 0, y: 0, z: 0}},
        'grass-plant-21': {name: 'grass-plant', position: {x: -1.25, y: -1.5, z: -0.5}, scale: 0.025, rotation: {x: 0, y: 0, z: 0}},
        'grass-plant-22': {name: 'grass-plant', position: {x: -1, y: -1.5, z: -0.5}, scale: 0.025, rotation: {x: 0, y: 0, z: 0}},
        'grass-plant-23': {name: 'grass-plant', position: {x: -0.75, y: -1.5, z: -0.5}, scale: 0.025, rotation: {x: 0, y: 0, z: 0}},
        'grass-plant-24': {name: 'grass-plant', position: {x: -0.5, y: -1.5, z: -0.5}, scale: 0.025, rotation: {x: 0, y: 0, z: 0}},
        'grass-plant-25': {name: 'grass-plant', position: {x: -0.25, y: -1.5, z: -0.5}, scale: 0.025, rotation: {x: 0, y: 0, z: 0}},
        'grass-plant-26': {name: 'grass-plant', position: {x: 0, y: -1.5, z: -0.5}, scale: 0.025, rotation: {x: 0, y: 0, z: 0}},
        'grass-plant-27': {name: 'grass-plant', position: {x: 0.25, y: -1.5, z: -0.5}, scale: 0.025, rotation: {x: 0, y: 0, z: 0}},
        'grass-plant-28': {name: 'grass-plant', position: {x: 0.5, y: -1.5, z: -0.5}, scale: 0.025, rotation: {x: 0, y: 0, z: 0}},
        'grass-plant-29': {name: 'grass-plant', position: {x: 0.75, y: -1.5, z: -0.5}, scale: 0.025, rotation: {x: 0, y: 0, z: 0}},
        'grass-plant-30': {name: 'grass-plant', position: {x: 1, y: -1.5, z: -0.5}, scale: 0.025, rotation: {x: 0, y: 0, z: 0}},
        'grass-plant-31': {name: 'grass-plant', position: {x: 1.25, y: -1.5, z: -0.5}, scale: 0.025, rotation: {x: 0, y: 0, z: 0}},
        'grass-plant-32': {name: 'grass-plant', position: {x: 1.5, y: -1.5, z: -0.5}, scale: 0.025, rotation: {x: 0, y: 0, z: 0}},
        'grass-plant-33': {name: 'grass-plant', position: {x: 1.75, y: -1.5, z: -0.5}, scale: 0.025, rotation: {x: 0, y: 0, z: 0}},
        'grass-plant-34': {name: 'grass-plant', position: {x: 2, y: -1.5, z: -0.5}, scale: 0.025, rotation: {x: 0, y: 0, z: 0}},
        'rock-1': {name: 'rock', position: {x: -1, y: -1.5, z: 0}, scale: 0.05, rotation: {x: 0, y: 0, z: 0}},
        'rock-2': {name: 'rock', position: {x: 0.25, y: -1.5, z: 0}, scale: 0.05, rotation: {x: 0, y: 0, z: 0}},
        'rock-3': {name: 'rock', position: {x: 1.5, y: -1.5, z: 0}, scale: 0.05, rotation: {x: 0, y: 0, z: 0}}

    }
};
